### ISSUE TITLE
Inconsistent handling of invalid image dimensions in upload flows

### ISSUE THREAD

**Issue by GreenReaper** [mucklet/mucklet-client#327]
When attempting to upload [a 0.99MiB WEBP area map](https://www.dropbox.com/scl/fi/57eoislo51wcrk1a17heq/c1back-half-linear-default-93.webp?rlkey=wrdm7w9d0oxlf166cl8thnmbt&st=hblzwvx4&dl=0) I was thwarted because it was 4176x600. However, this was only communicated via an "Uncaught (in promise)" exception in the console, rather than any visible error message:
```
method: "call.core.char.[character ID].ctrl.setAreaImage"
params:
 areaId: "[area ID]"
 uploadId: "...07lg"
 [[Prototype]]: Object
 rid: "core.char.[character ID].ctrl"
 _code: "file.dimensionsTooLarge"
 _data: {maxHeight: 4096, maxWidth: 4096}
 _message: "Image must not be larger than {maxWidth} × {maxHeight} pixels."
```

I expected this to have a popup box explaining the restriction, similar to the one that appears if you upload a file above 1MiB:
![Screenshot 2024-11-12 091637](https://github.com/user-attachments/assets/3cc33f2b-10aa-4a1a-b6ca-88bab9cfd732)

...or to be presented with a formatted message, as done in the Edit Character image flow which states on the Crop Image step:
> Image must not be larger than 4096 × 4096 pixels.

There's also a discrepancy in what you get in Crop Image of the Edit Character **Profile** page:
> Internal error: failed to create file core.char.img.[character ID]: Image must not be larger than {maxWidth} × {maxHeight} pixels.

-----
The original image is 8352x1200 but only ~3.6MB as WebP, since it is just 235 colours (intended for the 256-colour era of 1996) so could have been uploaded without scaling concerns if a) supporter and b) the limit were 16 MegaPixels rather than 4096x4096. (On the plus side, I found some [interesting details about WebP compression presets](https://gitlab.gnome.org/GNOME/gimp-help/-/issues/231#note_2275284) tuning the reduced-size version.)
